### ISSUE TITLE
byp4xx Head Request Error!

### ISSUE THREAD

**Issue by zyr1on** [lobuhi/byp4xx#12]
Hey. I just installed byp4xx (with git clone) and ran it for test something then I just realized there's an error on HEAD request tab.

Curl Version: curl 7.74.0 (x86_64-pc-linux-gnu) Release-Date: 2020-12-09.

Error Output: 
> [+]HTTP Methods...
> GET request: 404
> POST request: 404
> HEAD request: curl: option -m: expected a proper numerical parameter
> curl: try 'curl --help' or 'curl --manual' for more information

Line 74 and 77 -m flag has 1.0 value 
<code>74: STATUS=$(curl $REDIRECT -k -s -o /dev/null -m 1.0 -w "%{http_code}" -X HEAD $URL$DIR)</code>

Then I just changed the -m flag value 1.0 to 1 and its worked fine for me.
<code>74: STATUS=$(curl $REDIRECT -k -s -o /dev/null -m 1 -w "%{http_code}" -X HEAD $URL$DIR) </code>

> [+]HTTP Methods...
> GET request: 404
> POST request: 404
> HEAD request: 404

But in this section when a program comes to the head request tab to send request its waiting about 1 or 2 seconds longer than other requests.

Maybe it's not an error but I don't know.I just wanted to announce it :)
Best Regards.

**Comment by lobuhi** [comment]
Sure, this is realted to https://github.com/lobuhi/byp4xx/issues/9

According https://curl.se/docs/manpage.html#-m this is because you're using an old version of curl previous to 7.32.0.

I'll change it anyway! Thank you!

**Comment by zyr1on** [comment]
Thanks for your reply. You're right I got that. I'll update my curl.
Best Regards.
