### ISSUE TITLE
How to see what the payload is?

### ISSUE THREAD

**Issue by akhiljain029** [lobuhi/byp4xx#5]
As i got 200 ok what should be the payload for it [
<img width="236" alt="403bypass" src="https://user-images.githubusercontent.com/38918644/101239986-22ef9e00-3712-11eb-96b9-34ad0edf2c36.PNG">
](url)

**Comment by lobuhi** [comment]
Run:
./byp4xx.sh -c <url> 
So you will receive the entire curl command to check on your own.
