### ISSUE TITLE
Suggestion: Factorize code a bit

### ISSUE THREAD

**Issue by gmt4** [lobuhi/byp4xx#8]
Just as a suggestion for improvement:

Code could use a bit of factorization, for example: factoring when testing the HTTP methods, see the example in the https://gist.github.com/gmt4/59ae5b6b74b4d599044d6739040ccd05.

Best!

**Comment by lobuhi** [comment]
I'm not used to functions on bash, but ur code rocks! I'll take in consideration ur suggestion and maybe I'll update later. Thx!
