### ISSUE TITLE
HEAD request: curl: option -m: expected a proper numerical parameter

### ISSUE THREAD

**Issue by marcosdell** [lobuhi/byp4xx#9]
Hello! :)

When running this:

> _$ ./byp4xx.sh -r -c https://www.test.com_

I'm getting this:

> [+]HTTP Methods...
> GET request: 403
> POST request: 403
> **HEAD request: curl: option -m: expected a proper numerical parameter
> curl: try 'curl --help' or 'curl --manual' for more information**

The byp4xx.sh uses the following command, with the -m option:

> echo -n "HEAD request: "
> STATUS=$(curl $REDIRECT -k -s -o /dev/null -m 1.0 -w "%{http_code}" -X HEAD $URL$DIR)

If I change to **-m 1** (instead of 1.0), it works without the message above.

My setup:

$ uname -r               
5.9.0-kali1-amd64

$ curl -V    
curl 7.72.0 (x86_64-pc-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.8.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-08-19

Thanks!

**Comment by lobuhi** [comment]
Pull request accepted. Thx!
